=== chetan03tutorial/gozo/sales-api/src/main/resources/config/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root (section+)>
<!ELEMENT section (#PCDATA | tag)*>
<!ELEMENT tag (#PCDATA | value)*>
<!ELEMENT value (#PCDATA)>
<!ATTLIST tag type CDATA #IMPLIED>
<!ATTLIST value type CDATA #IMPLIED>

<!--===============================================================================================-->
<!-- Entities -->
<!--===============================================================================================-->
<!--===============================================================================================-->
<!ENTITY URL_CMS_SERVER "http://10.245.225.17:10051">
<!ENTITY WA_PROVIDER_DOMAIN "statse.webtrendslive.com">
<!ENTITY WA_PROVIDER_DATASOURCE "dcsq8h85v000004zdphfmh9ls_6o3l">
<!ENTITY WA_PROVIDER_FIRST_PARTY_COOKIE_DOMAIN "test.lloydstsb.co.uk">
<!ENTITY WA_PROVIDER_ENABLED "false">
<!ENTITY GALAXY_LOG_DIR "${GalaxyLogDir}">
<!ENTITY URL_REFERER_INITIAL_REQUEST "https://ibglxystc-ltsb.test.lloydstsb.co.uk$$$https://ibglxystc-ltsbbusiness.test.lloydstsb.co.uk$$$https://ibglxystc.bos.test.lloydstsb.co.uk$$$https://ibglxystc-bosbusiness.test.lloydstsb.co.uk$$$https://ibglxystc-halifax.test.lloydstsb.co.uk$$$https://llgb-p1dc-dpw-wf07-eth0.test.lloydstsb.co.uk$$$https://galhsm.test.lloydstsb.co.uk$$$https://this.url.used.for.live.do.not.remove">
<!ENTITY URL_REFERER_OTHER_REQUEST "https://ibglxystc-ltsb.test.lloydstsb.co.uk$$$https://ibglxystc-ltsbbusiness.test.lloydstsb.co.uk$$$https://ibglxystc.bos.test.lloydstsb.co.uk$$$https://ibglxystc-bosbusiness.test.lloydstsb.co.uk$$$https://ibglxystc-halifax.test.lloydstsb.co.uk$$$https://llgb-p1dc-dpw-wf07-eth0.test.lloydstsb.co.uk$$$https://galhsm.test.lloydstsb.co.uk$$$https://this.url.used.for.live.do.not.remove">
<!ENTITY FORCED_LOGOFF_REDIRECT_URL "/sorry/pages/error.html">
<!ENTITY INVALID_SESSION_FORCED_LOGOFF_REDIRECT_URL "https://ibglxystc-ltsb.test.lloydstsb.co.uk:16222">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_LOGIN "/">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_1 "/sorry/pages/error.html">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_2 "/unauth/pages/customersecuritylogoff.jsp">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_3 "/unauth/pages/errorpageauthenticationfailed.jsp">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_UNAVAILABLE_PAGE "/sorry/pages/unavailable.html">
<!ENTITY URL_AUTH_SERVER "https://llgb-p1dc-dpw-wf07-eth0.test.lloydstsb.co.uk:16223/personal/login">
<!ENTITY URL_LTSB_RETAIL "https://ibglxystc-ltsb.test.lloydstsb.co.uk:16232/personal">
<!ENTITY URL_BOS_RETAIL "https://ibglxystc.bos.test.lloydstsb.co.uk:16232/InternetBankingUnauthWEB">
<!ENTITY COOKIES_DOMAIN ".lloydstsb.co.uk">
<!ENTITY THROTTLE_COOKIES_NAME "IBCOOKIE01">
<!ENTITY APPLICATION_LOGGING_MODE "UA">
<!ENTITY AUTH_SITE "false">
<!ENTITY TRAVEL_MONEY_BRANCH_FINDER_KEY "AvvQOc_Gq6nyV_8mWKgCcCe9aGXU6N6NhNptoM6_XvzWGBZYbcVx2rTX_HDFE-KT">
<!ENTITY MULTIMAP_URL_PREFIX "https://dev.virtualearth.net/REST/v1/Imagery/Map/Road/">
<!ENTITY MULTIMAP_URL_POSTFIX "&amp;err=No+map+available.&amp;width=250&amp;height=250&amp;scale=10000">
<!ENTITY STACK "UNAS">

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configCookiesAttributes.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>  
    <section>INITIAL_REQUEST_COOKIES
        <tag>REDIRECT_COOKIE_KEY
            <value>REDIRECT_COOKIE</value>
        </tag>
    </section>  
    
    <section>OTHER_REQUEST_COOKIES
        <tag>IBSESSION_COOKIE_KEY
            <value>IBSESSION_COOKIE</value>
        </tag>
        <tag>LOGOFF_COOKIE_KEY
            <value>LOGOFF_COOKIE</value>
        </tag>
        <tag>LTPATOKEN_COOKIE_KEY
            <value>LTPATOKEN_COOKIE</value>
        </tag>
        <tag>JSESSIONID_COOKIE_KEY
            <value>JSESSIONID_COOKIE</value>
        </tag>
    </section>  
    
    <section>REDIRECT_COOKIE
        <tag>NAME
            <value>redirect</value>
        </tag>
        <tag>VALUE
            <value>[0-9a-zA-Z+?.,%*:;"(){} /-]*</value>
        </tag>
        <tag>DOMAIN
            <value>.lloydstsb.co.uk</value>
        </tag>
        <tag>PATH
            <value>/</value>
        </tag>
        <tag>SECURE
            <value>true</value>
        </tag>
    </section>  

    <section>IBSESSION_COOKIE
        <tag>NAME
            <value>IBSESSION</value>
        </tag>
        <tag>VALUE
            <value>[0-9a-zA-Z+?.,%*:;"(){} /-]*</value>
        </tag>
        <tag>DOMAIN
            <value>.lloydstsb.co.uk</value>
        </tag>
        <tag>PATH
            <value>/</value>
        </tag>
        <tag>SECURE
            <value>true</value>
        </tag>
    </section>  

    <section>LOGOFF_COOKIE
        <tag>NAME
            <value>logoff</value>
        </tag>
        <tag>VALUE
            <value>[0-9a-zA-Z+?.,%*:;"(){} /-]*</value>
        </tag>
        <tag>DOMAIN
            <value>.lloydstsb.co.uk</value>
        </tag>
        <tag>PATH
            <value>/</value>
        </tag>
        <tag>SECURE
            <value>true</value>
        </tag>
    </section>  

    <section>LTPATOKEN_COOKIE
        <tag>NAME
            <value>LtpaToken2</value>
        </tag>
        <tag>VALUE
            <value>[0-9a-zA-Z+?.,%*:;"(){} /-]*</value>
        </tag>
        <tag>DOMAIN
            <value>.lloydstsb.co.uk</value>
        </tag>
        <tag>PATH
            <value>/</value>
        </tag>
        <tag>SECURE
            <value>true</value>
        </tag>
    </section>  

    <section>JSESSIONID_COOKIE
        <tag>NAME
            <value>JSESSIONID</value>
        </tag>
        <tag>VALUE
            <value>[0-9a-zA-Z+?.,%*:;"(){} /-]*</value>
        </tag>
        <tag>DOMAIN
            <value>.lloydstsb.co.uk</value>
        </tag>
        <tag>PATH
            <value>/</value>
        </tag>
        <tag>SECURE
            <value>true</value>
        </tag>
    </section>

    <section>
        EXPECTED_COOKIES
        <tag>
            REDIRECT_COOKIE
            <value>redirect</value>
        </tag>
        <tag>
            IBSESSION_COOKIE
            <value>IBSESSION</value>
        </tag>
        <tag>
            LOGOFF_COOKIE
            <value>logoff</value>
        </tag>
        <tag>
            LTPATOKEN_COOKIE
            <value>LtpaToken2</value>
        </tag>
        <tag>
            JSESSIONID_COOKIE
            <value>JSESSIONID</value>
        </tag>
        <tag>
            THROTTLE_COOKIE
            <value>&THROTTLE_COOKIES_NAME;</value>
        </tag>
        <tag>
            INDRA_COOKIE
            <value>pp</value>
        </tag>
        <tag>
            PHISHING_COOKIE
            <value>IBCOOKIE02</value>
        </tag>
        <tag>
            dcConnector_COOKIE
            <value>dcConnector</value>
        </tag>
        <tag>
            WT_FPC_COOKIE
            <value>WT_FPC</value>
        </tag>
        <tag>
            ShortTimeoutInterval_COOKIE
            <value>ShortTimeoutInterval</value>
        </tag>
        <tag>
            IBCcookieID_COOKIE
            <value>IBCcookieID</value>
        </tag>
        <tag>
            IBCBrandContext_COOKIE
            <value>IBCBrandContext</value>
        </tag>
        <tag>
            IBCUserID_COOKIE
            <value>IBCUserID</value>
        </tag>
        <tag>
            E_PRIVACY_COOKIE
            <value>IBCOOKIE03</value>
        </tag>
        <tag>
            MORTGAGE_COOKIE_COLLEAGUE_ID
            <value>IBMortgageColleagueID</value>
        </tag>
    </section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configBrandChannelMapping.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
    <section>PRODUCT_BRAND
        <tag>
        LLOYDS             
        <value>IBL</value>	
        </tag>
         <tag>
        HALIFAX
        <value>IBH</value>		
         </tag>
        <tag>
        BOS
         <value>IBS</value>		
         </tag>
         <tag>
        VERDE
        <value>IBV</value>
        </tag>
     </section>
     <section>BRAND_NAME_MAPPING
        <tag>
        IBL
        <value>LTB</value>
        </tag>
         <tag>
        IBH
        <value>HAL</value>
         </tag>
        <tag>
        IBS
         <value>BOS</value>
         </tag>
         <tag>
        IBV
        <value>TSB</value>
        </tag>
     </section>
    <section>BRAND_CODE_MAPPING
        <tag>
            LTB
            <value>106</value>
        </tag>
        <tag>
            HAL
            <value>107</value>
        </tag>
        <tag>
            BOS
            <value>108</value>
        </tag>
    </section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configLogActivityEvents.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
	<section>
		A10001
		<tag>
			EVENT_NAME
			<value>configuration.parse</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10002
		<tag>
			EVENT_NAME
			<value>state.refdata</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10003
		<tag>
			EVENT_NAME
			<value>configfile.loaded</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10004
		<tag>
			EVENT_NAME
			<value>prefetchworker.startwork</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10005
		<tag>
			EVENT_NAME
			<value>navrules.loaded</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10006
		<tag>
			EVENT_NAME
			<value>bookmarkrules.loaded</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10007
		<tag>
			EVENT_NAME
			<value>ajaxrules.loaded</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10008
		<tag>
			EVENT_NAME
			<value>servicetype.set</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10009
		<tag>
			EVENT_NAME
			<value>channelvalue.set</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10010
		<tag>
			EVENT_NAME
			<value>brandvalue.set</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10011
		<tag>
			EVENT_NAME
			<value>content.notfound</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10012
		<tag>
			EVENT_NAME
			<value>devicecapability.activitylog</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		MF0001
		<tag>
			EVENT_NAME
			<value>ManagementFramework.logLevelChanged</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>
	<section>
		A10013
		<tag>
			EVENT_NAME
			<value>syncToken.doubleSubmitDetected</value>
		</tag>
		<tag>
			ENABLED
			<value>1</value>
		</tag>
	</section>

</root>

=== chetan03tutorial/gozo/sales-api/src/test/resources/config/configApiServicePropertiesLISA_AFT.xml
<?xml version="1.0"?>
<!DOCTYPE root SYSTEM "./config.dtd">
<root>
      <section>
            API_SERVICE_ENDPOINTS
            <tag>
                  ADDRESS_SEARCH
                  <value>http://apptuvirtual054.machine.test.group:12305/aft/InformationProvisionService</value>
            </tag>
            <tag>
                  RETRIEVE_PRODUCT_FEATURES
                  <value>http://apptuvirtual054.machine.test.group:12301/aft/retrieveProductConditions</value>
            </tag>
            <tag>
                  ARRANGE_PRODUCT
                  <value>http://apptuvirtual054.machine.test.group:12302/aft/offerProductArrangement</value>
            </tag>
            <tag>
                  ACTIVATE_PRODUCT_ARRANGEMENT
                  <value>http://apptuvirtual054.machine.test.group:12304/aft/productActivation</value>
            </tag>
            <tag>
                  USERNAME_VALIDATION
                  <value>http://10.245.211.198:8731</value>
            </tag>
            <tag>
            	THREAT_MATRIX
            	<value>http://10.245.211.251:22910/host/threadmatrix/</value>
            </tag>
            <tag>
            	BAPI_AUDITING
            	<value>http://10.245.211.198:8731/fserv/</value>
             </tag>
      </section>
      <section>
            DEVICE_URL
            <tag>
                  LLOYDS
                  <value>https://check2.lloydsbank.co.uk</value>
            </tag>
            <tag>
                  HALIFAX
                  <value>https://check2.halifax-online.co.uk</value>
            </tag>
            <tag>
                  BOS
                  <value>https://check2.bankofscotland.co.uk</value>
            </tag>
            <tag>
                  VERDE
                  <value>https://check2.tsb.co.uk</value>
            </tag>
            <tag>
                  LLOYDSBANK
                  <value>https://check2.lloydsbank.co.uk</value>
            </tag>
      </section>
      <section>
            THREAT_MATRIX_ORG_ID
            <tag>
                  LLOYDS
                  <value>g17j1ysn</value>
            </tag>
            <tag>
                  HALIFAX
                  <value>g17j1ysn</value>
            </tag>
            <tag>
                  BOS
                  <value>g17j1ysn</value>
            </tag>
            <tag>
                  LLOYDSBANK
                  <value>g17j1ysn</value>
            </tag>
            <tag>
                  VERDE
                  <value>8vzkivup</value>
            </tag>
      </section>
      <section>
            TIMEOUTS
            <tag>
                  SOAP_COMMUNICATOR_TIMEOUT_IN_MILLIS
                  <value>5000</value>
            </tag>
            <tag>
                  CONTENT_SERVICE_BACKEND_CALL_TIMEOUT_IN_MILLIS
                  <value>5000</value>
            </tag>
      </section>
	<section>
		API_SERVICE_ENDPOINTS
		<tag>
			ADDRESS_SEARCH
			<value>http://apptuvirtual054.machine.test.group:12305/aft/InformationProvisionService</value>
		</tag>
		<tag>
			RETRIEVE_PRODUCT_FEATURES
			<value>http://apptuvirtual054.machine.test.group:12301/aft/retrieveProductConditions</value>
		</tag>
		<tag>
			ARRANGE_PRODUCT
			<value>http://apptuvirtual054.machine.test.group:12302/aft/offerProductArrangement</value>
		</tag>
		<tag>
			ACTIVATE_PRODUCT_ARRANGEMENT
			<value>http://apptuvirtual054.machine.test.group:12304/aft/productActivation</value>
		</tag>
		<tag>
			USERNAME_VALIDATION
			<value>http://10.245.211.198:8731</value>
		</tag>
	</section>
	<section>
		DEVICE_URL
		<tag>
			LLOYDS
			<value>https://check2.lloydsbank.co.uk</value>
		</tag>
		<tag>
			HALIFAX
			<value>https://check2.halifax-online.co.uk</value>
		</tag>
		<tag>
			BOS
			<value>https://check2.bankofscotland.co.uk</value>
		</tag>
		<tag>
			VERDE
			<value>https://check2.tsb.co.uk</value>
		</tag>
		<tag>
			LLOYDSBANK
			<value>https://check2.lloydsbank.co.uk</value>
		</tag>
	</section>
	<section>
		THREAD_METRIX_ORG_ID
		<tag>
			LLOYDS
			<value>g17j1ysn</value>
		</tag>
		<tag>
			HALIFAX
			<value>g17j1ysn</value>
		</tag>
		<tag>
			BOS
			<value>g17j1ysn</value>
		</tag>
		<tag>
			LLOYDSBANK
			<value>g17j1ysn</value>
		</tag>
		<tag>
			VERDE
			<value>8vzkivup</value>
		</tag>
	</section>
	<section>
		CONTENTSERVICE_URL_BRAND_NSP
		<tag>
			LTSBRetail
			<value>LLOYDS/</value>
		</tag>
		<tag>
			BOSRetail
			<value>BOS/</value>
		</tag>
	</section>
	<section>
			CONTENTSERVICE_URL_RESOURCE_BUNDLE_NSP
		<tag>
			LTSBRetail
			<value>lloydsResource</value>
		</tag>
		<tag>
			BOSRetail
			<value>bosResource</value>
		</tag>
	</section>
	<section>
		IIS_CMS_SERVER_URL_NSP
		<tag>
			LTSBRetail
			<value>http://appduv00bd.machine.test.group:7772/</value>
		</tag>
		<tag>
			BOSRetail
			<value>http://appduv00bd.machine.test.group:7772/</value>
		</tag>
	</section>
	<section>
		CONTENT
		<tag>
			LTSBRetail
			<value>http://appduv00bd.machine.test.group:7772/LLOYDS/</value>
		</tag>
		<tag>
			BOSRetail
			<value>http://appduv00bd.machine.test.group:7772/BOS/</value>
		</tag>
	</section>
	<section>
		TIMEOUTS
		<tag>
			SOAP_COMMUNICATOR_TIMEOUT_IN_MILLIS
			<value>5000</value>
		</tag>
		<tag>
			CONTENT_SERVICE_BACKEND_CALL_TIMEOUT_IN_MILLIS
			<value>5000</value>
		</tag>
	</section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configSessionEndListener.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
    <section>SESSION_END_HEADER_CONFIG
        <!-- Text in <value> tag will be used to set log off header name.  -->
        <tag>HEADER_NAME_KEY
            <value>UNAUTH_END_SESSION</value>
        </tag>
        <!-- Text in <value> tag will be used to set log off header value.  -->     
        <tag>HEADER_VALUE_KEY
            <value>YES</value>
        </tag>
    </section>

    <!-- This section contains view-id of pages for which log off header needs to be sent. -->
    <section>SESSION_END_HEADER_PAGE_ID
        <tag>PAGE_ONE_KEY
            <value>/submitforgottenuserid/forgotUserIDsuccess.jsp</value>
        </tag>
        <tag>PAGE_TWO_KEY
            <value>/submitreplaceunlockauthmechanism/successpasswordreset.jsp</value>
        </tag>
        <tag>PAGE_THREE_KEY
            <value>/registration/applicationalreadyplaced.jsp</value>
        </tag>
        <tag>PAGE_FOUR_KEY
            <value>/registration/helpdeskauthorization.jsp</value>
        </tag>
        <tag>PAGE_FIVE_KEY
            <value>/registration/successregistration.jsp</value>
        </tag>
        <tag>PAGE_SIX_KEY
            <value>/registration/registrationsuccessfull.jsp</value>
        </tag>
        <tag>PAGE_SEVEN_KEY
            <value>/registration/registrationdecline.jsp</value>
        </tag>
        <tag>PAGE_EIGHT_KEY
            <value>/submitreplaceunlockauthmechanism/addressdetailsrequiredmessage.jsp</value>
        </tag>
        <tag>PAGE_NINE_KEY
            <value>/submitreplaceunlockauthmechanism/addressdetailsrequiredmessageretail.jsp</value>
        </tag>      
        <tag>PAGE_TEN_KEY
            <value>/submitreplaceunlockauthmechanism/applicationalreadyreceived.jsp</value>
        </tag>      
        <tag>PAGE_ELEVEN_KEY
            <value>/submitreplaceunlockauthmechanism/partialsuccess.jsp</value>
        </tag>
        <tag>PAGE_TWELVE_KEY
            <value>/submitreplaceunlockauthmechanism/partialsuccessincorrectcode.jsp</value>
        </tag>
        <tag>PAGE_THIRTEEN_KEY
            <value>/submitreplaceunlockauthmechanism/partialsuccessnomandate.jsp</value>
        </tag>
        <tag>PAGE_FOURTEEN_KEY
            <value>/submitreplaceunlockauthmechanism/partialsuccessnophonenumber.jsp</value>
        </tag>
        <tag>PAGE_FIFTEEN_KEY
            <value>/submitreplaceunlockauthmechanism/partialsuccessnoresponse.jsp</value>
        </tag>
        <tag>PAGE_SIXTEEN_KEY
            <value>/submitreplaceunlockauthmechanism/successdeviceunlocked.jsp</value>
        </tag>
        <tag>PAGE_SEVENTEEN_KEY
            <value>/submitreplaceunlockauthmechanism/successorderreplacementdevice.jsp</value>
        </tag>
        <tag>PAGE_EIGHTEEN_KEY
            <value>/submitreplaceunlockauthmechanism/successpasswordandmireset.jsp</value>
        </tag>
        <tag>PAGE_NINETEEN_KEY
            <value>/logon/loginIB.jsp</value>
        </tag>  
    </section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configLogFactory.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>	
	<section>LOGGER_FACTORY		
		<tag>
			SERVICE_LOGGER
			<value>com.lloydstsb.ea.logging.impl.LoggingServiceImpl</value>
		</tag>
		<tag>
			ACTIVITY_LOGGER
			<value>com.lloydstsb.ea.logging.impl.ActivityLoggerImpl</value>
		</tag>
		<tag>
			AUDIT_LOGGER
			<value>com.lloydstsb.ea.logging.impl.AuditLoggerImpl</value>
		</tag>
		<tag>
			DEBUG_LOGGER
			<value>com.lloydstsb.ea.logging.impl.DebugLoggerImpl</value>
		</tag>
		<tag>
			ERROR_LOGGER
			<value>com.lloydstsb.ea.logging.impl.ErrorLoggerImpl</value>
		</tag>
		<tag>
			METRIC_LOGGER
			<value>com.lloydstsb.ea.logging.impl.MetricLoggerImpl</value>
		</tag>
		<tag>
			PERFORMANCE_LOGGER
			<value>com.lloydstsb.ea.logging.impl.PerformanceLoggerImpl</value>
		</tag>
		<tag>
			STATE_LOGGER
			<value>com.lloydstsb.ea.logging.impl.StateLoggerImpl</value>
		</tag>
		<tag>
			TRACE_LOGGER
			<value>com.lloydstsb.ea.logging.impl.TraceLoggerImpl</value>
		</tag>
		<tag>
			WARNING_LOGGER
			<value>com.lloydstsb.ea.logging.impl.WarningLoggerImpl</value>
		</tag>
		<tag>
			EXCEPTION_LOGGER
			<value>com.lloydstsb.ea.logging.impl.ExceptionLoggerImpl</value>
		</tag>
		<tag>
			ALERT_LOGGER
			<value>com.lloydstsb.ea.logging.impl.AlertLoggerImpl</value>
		</tag>
	</section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configRestfulServices.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
    <section>PATH
        <tag>
            RESTFUL_SERVICES_PATH                                    
            <value>/sales-pca-api/v2</value>
        </tag>
    </section>
    <section>LOGIN_SERVICE
        <tag>
            METHOD                                     
            <value>POST</value>               
        </tag>
        <tag>
            URL
            <value>/session</value>
        </tag>
    </section>
    <section>LIGHT_LOGIN_SERVICE
        <tag>
            METHOD                                     
            <value>GET</value>                
        </tag>
        <tag>
            URL
            <value>/session/token</value>
        </tag>
    </section>
        <section>
        REST_VALIDATOR
        <tag>
            JSON_ERROR
            <value>{"code":"9213429","message":"9213429: Sorry, a
                technical error has occurred. Please return to home page and
                try again.","category":"FORCED_LOGOUT"}</value>
        </tag>
    </section>
    
    <section>NGA_VALIDATOR
        <tag>
            JSON_ERROR                                     
            <value>{"code":"9213429","message":"9213429: Sorry, a technical error has occurred. Please return to login and try again.","category":"FORCED_LOGOUT"}</value>                
        </tag>
        <tag>
            APP_NAME
            <value>NGA</value>
        </tag>
    </section>
    <section>
        TNGA_VALIDATOR
        <tag>
            JSON_ERROR
            <value>{"code":"9213429","message":"9213429: Sorry, a
                technical error has occurred. Please return to login and
                try again.","category":"FORCED_LOGOUT"}</value>
        </tag>
        <tag>
            APP_NAME
            <value>TNGA</value>
        </tag>
    </section>
    <section>
        CNGA_VALIDATOR
        <tag>
            JSON_ERROR
            <value>{"code":"9213429","message":"9213429: Sorry, a
                technical error has occurred. Please return to login and
                try again.","category":"FORCED_LOGOUT"}</value>
        </tag>
        <tag>
            APP_NAME
            <value>CNGA</value>
        </tag>
    </section>
    <section>MEMORABLE_CHARACTERS
        <tag>
            METHOD
            <value>GET</value>
        </tag>
        <tag>
            URL
            <value>/session/memorablecharacters</value>
        </tag>
    </section>
    <!-- BNGA -->
    <section>EVENT_AUTHENICATION
        <tag>
            METHOD
            <value>GET</value>
        </tag>
        <tag>
            URL
            <value>/contentdata</value>
        </tag>
    </section>
    <section>SECURITY_FILTER
        <tag>
            EXPLICIT_SESSION_CREATION_FOR_PATHS
            <value>/</value>
        </tag>
    </section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configInvocationHandler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
      <section>
            DAO_INVOCATION_HANDLER
            <tag>
                  DAOTHROTTLE
                   <value>ThrottleBehavior</value>
            </tag>            
      </section>
      <section>
            ThrottleBehavior
            <tag>
                  ClassName
                   <value>com.lloydstsb.ea.dao.dynamicproxies.DAOThrottleBehavior</value>
            </tag>
            <tag>
                  Order
                   <value>1</value>
            </tag>            
      </section>      
</root>
