=== chetan03tutorial/gozo/sales-api/src/main/resources/config/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root (section+)>
<!ELEMENT section (#PCDATA | tag)*>
<!ELEMENT tag (#PCDATA | value)*>
<!ELEMENT value (#PCDATA)>
<!ATTLIST tag type CDATA #IMPLIED>
<!ATTLIST value type CDATA #IMPLIED>

<!--===============================================================================================-->
<!-- Entities -->
<!--===============================================================================================-->
<!--===============================================================================================-->
<!ENTITY URL_CMS_SERVER "http://10.245.225.17:10051">
<!ENTITY WA_PROVIDER_DOMAIN "statse.webtrendslive.com">
<!ENTITY WA_PROVIDER_DATASOURCE "dcsq8h85v000004zdphfmh9ls_6o3l">
<!ENTITY WA_PROVIDER_FIRST_PARTY_COOKIE_DOMAIN "test.lloydstsb.co.uk">
<!ENTITY WA_PROVIDER_ENABLED "false">
<!ENTITY GALAXY_LOG_DIR "${GalaxyLogDir}">
<!ENTITY URL_REFERER_INITIAL_REQUEST "https://ibglxystc-ltsb.test.lloydstsb.co.uk$$$https://ibglxystc-ltsbbusiness.test.lloydstsb.co.uk$$$https://ibglxystc.bos.test.lloydstsb.co.uk$$$https://ibglxystc-bosbusiness.test.lloydstsb.co.uk$$$https://ibglxystc-halifax.test.lloydstsb.co.uk$$$https://llgb-p1dc-dpw-wf07-eth0.test.lloydstsb.co.uk$$$https://galhsm.test.lloydstsb.co.uk$$$https://this.url.used.for.live.do.not.remove">
<!ENTITY URL_REFERER_OTHER_REQUEST "https://ibglxystc-ltsb.test.lloydstsb.co.uk$$$https://ibglxystc-ltsbbusiness.test.lloydstsb.co.uk$$$https://ibglxystc.bos.test.lloydstsb.co.uk$$$https://ibglxystc-bosbusiness.test.lloydstsb.co.uk$$$https://ibglxystc-halifax.test.lloydstsb.co.uk$$$https://llgb-p1dc-dpw-wf07-eth0.test.lloydstsb.co.uk$$$https://galhsm.test.lloydstsb.co.uk$$$https://this.url.used.for.live.do.not.remove">
<!ENTITY FORCED_LOGOFF_REDIRECT_URL "/sorry/pages/error.html">
<!ENTITY INVALID_SESSION_FORCED_LOGOFF_REDIRECT_URL "https://ibglxystc-ltsb.test.lloydstsb.co.uk:16222">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_LOGIN "/">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_1 "/sorry/pages/error.html">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_2 "/unauth/pages/customersecuritylogoff.jsp">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_3 "/unauth/pages/errorpageauthenticationfailed.jsp">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_UNAVAILABLE_PAGE "/sorry/pages/unavailable.html">
<!ENTITY URL_AUTH_SERVER "https://llgb-p1dc-dpw-wf07-eth0.test.lloydstsb.co.uk:16223/personal/login">
<!ENTITY URL_LTSB_RETAIL "https://ibglxystc-ltsb.test.lloydstsb.co.uk:16232/personal">
<!ENTITY URL_BOS_RETAIL "https://ibglxystc.bos.test.lloydstsb.co.uk:16232/InternetBankingUnauthWEB">
<!ENTITY COOKIES_DOMAIN ".lloydstsb.co.uk">
<!ENTITY THROTTLE_COOKIES_NAME "IBCOOKIE01">
<!ENTITY APPLICATION_LOGGING_MODE "UA">
<!ENTITY AUTH_SITE "false">
<!ENTITY TRAVEL_MONEY_BRANCH_FINDER_KEY "AvvQOc_Gq6nyV_8mWKgCcCe9aGXU6N6NhNptoM6_XvzWGBZYbcVx2rTX_HDFE-KT">
<!ENTITY MULTIMAP_URL_PREFIX "https://dev.virtualearth.net/REST/v1/Imagery/Map/Road/">
<!ENTITY MULTIMAP_URL_POSTFIX "&amp;err=No+map+available.&amp;width=250&amp;height=250&amp;scale=10000">
<!ENTITY STACK "UNAS">

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configForcedLogoffRedirectURLs.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
    <section>FORCED_LOGOFF_REDIRECT_URLS
        <tag>
            FORCED_LOGOFF_REDIRECT_TO_LOGIN 
            <value>&FORCED_LOGOFF_REDIRECT_TO_LOGIN;</value>                                   
        </tag>
        <tag>
            FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_1   
            <value>&FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_1;</value>                                 
        </tag>
        <tag>
            FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_2 
            <value>&FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_2;</value>                                   
        </tag>
        <tag>
            FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_3   
            <value>&FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_3;</value>                                 
        </tag>
        <tag>
            FORCED_LOGOFF_REDIRECT_TO_UNAVAILABLE_PAGE   
            <value>&FORCED_LOGOFF_REDIRECT_TO_UNAVAILABLE_PAGE;</value>                                 
        </tag>
    </section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configBrandServiceTypeChannels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
	<section>
		LLOYDS
		<tag>
			RETAIL
			<value>LTSBRetail</value>
		</tag>
		<tag>
			COMMERCIAL
			<value>LTSBCommercial</value>
		</tag>
	</section>
	<section>
		BOS
		<tag>
			RETAIL
			<value>BOSRetail</value>
		</tag>
		<tag>
			COMMERCIAL
			<value>BOSCommercial</value>
		</tag>
	</section>
	<section>
		HALIFAX
		<tag>
			RETAIL
			<value>HalifaxRetail</value>
		</tag>
	</section>
	<!-- Verde Changes - UI layer - starts -->
	<section>
		VERDE
		<tag>
			RETAIL
			<value>VerdeRetail</value>
		</tag>
		<tag>
			COMMERCIAL
			<value>VerdeCommercial</value>
		</tag>
	</section>
	<!-- Verde Changes - UI layer - ends -->
	<!-- Entries added for Multichannel Project - Starts -->
	<section>
		POINT_OF_ORIGIN
		<tag>
			BRANCH
			<value>Branch</value>
		</tag>
		<tag>
			TELEPHONY
			<value>Telephony</value>
		</tag>
	</section>
	<!--  Entries added for Multichannel Project - Ends -->
	<!-- Multichannel COM1 validation entry start here -->
	<section>
		POINT_OF_ORIGIN_SCOPE
		<tag>
			SCOPE
			<value>SESSION</value>
			<!--  The possible values for POINT_OF_ORIGIN_SCOPE are - SESSION.-->
		</tag>
	</section>
	<section>
		POINT_OF_ORIGIN_VALIDATION
		<tag>
			ENABLED
			<value>1</value>
			<!--  The possible values are 1- Enabled, 2- Disabled -->
		</tag>
		<tag>
			POINT_OF_ORIGIN_VALIDATION_CLASS
			<value>com.lloydstsb.ea.validator.PointOfOriginValidator</value>
			<!--  Fully qualified name of brand validator class, this class should implement IValidator Command-->
		</tag>
	</section>
	<!-- Multichannel COM1 validation entry end here -->
	
	<section>
	   CHANNEL_ID
	   <tag>
	       LTSBRetail
	       <value>IBL</value>
	   </tag>
	   <tag>
	       BOSRetail
	       <value>IBS</value>
	   </tag>
	   <tag>
	       HalifaxRetail
	       <value>IBH</value>
	   </tag>
	   <tag>
	       VerdeRetail
	       <value>IBV</value>
	   </tag>
	   <tag>
	       LTSBCommercial
	       <value>STL</value>
	   </tag>
	   <tag>
	       BOSCommercial
	       <value>STS</value>
	   </tag>
	   <tag>
	       VerdeCommercial
	       <value>STV</value>
	   </tag>
	</section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configProductListPerBrand.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
	<!---LLOYDS PRODUCTS-->
	<section>
		PRODUCTS_LLOYDS_ED
		<tag>
			FIRST
			<value>P_CLASSIC</value>
		</tag>
		<tag>
			SECOND
			<value>P_PLAT_CLB</value>
		</tag>
		<tag>
			THIRD
			<value>P_NEW_BASIC</value>
		</tag>
		<tag>
			FOURTH
			<value>P_CLUB</value>
		</tag>
		<tag>
			FIFTH
			<value>P_PLAT</value>
		</tag>
	</section>

	<section>
		PRODUCTS_LLOYDS_STUDENT
		<tag>
			FIRST
			<value>P_NEW_BASIC</value>
		</tag>
		<tag>
			SECOND
			<value>P_STUDENT</value>
		</tag>

	</section>

	<section>
		PRODUCTS_LLOYDS_YOUTH
		<tag>
			FIRST
			<value>P_UNDER19</value>
		</tag>
	</section>
	<!---END LLOYDS PRODUCTS-->

	<!---BOS PRODUCTS-->
	<section>
		PRODUCTS_BOS_ED
		<tag>
			FIRST
			<value>P_CLASSIC</value>
		</tag>
		<tag>
			SECOND
			<value>P_NEW_BASIC</value>
		</tag>

		<tag>
			THIRD
			<value>P_PLAT</value>
		</tag>
	</section>

	<section>
		PRODUCTS_BOS_STUDENT
		<tag>
			FIRST
			<value>P_STUDENT</value>
		</tag>
		<tag>
			SECOND
			<value>P_NEW_BASIC</value>
		</tag>
	</section>

	<section>
		PRODUCTS_BOS_YOUTH
		<tag>
			FIRST
			<value>P_UNDER19</value>
		</tag>
	</section>
	<!---END BOS PRODUCTS-->

	<!---HALIFAX PRODUCTS-->
	<section>
		PRODUCTS_HALIFAX_ED
		<tag>
			FIRST
			<value>P_REWARD</value>
		</tag>
		<tag>
			SECOND
			<value>P_ULTIMATE</value>
		</tag>
		<tag>
			THIRD
			<value>P_NEW_BASIC</value>
		</tag>
	</section>

	<section>
		PRODUCTS_HALIFAX_STUDENT
		<tag>
			FIRST
			<value>P_STUDENT</value>
		</tag>
		<tag>
			SECOND
			<value>P_NEW_BASIC</value>
		</tag>
	</section>

	<section>
		PRODUCTS_HALIFAX_YOUTH
		<tag>
			FIRST
			<value>P_EXPRESSCASH</value>
		</tag>
	</section>
	<!---END HALIFAX PRODUCTS-->
	
	<!---BANKRUPTCY PRODUCTS-->
	<section>
		BANKRUPTCY_PRODUCT_KEY
		<tag>
			FIRST
			<value>P_NEW_BASIC</value>
		</tag>
		<tag>
			SECOND
			<value>P_CLASSIC</value>
		</tag>
	</section>
	
	<section>
		HALIFAX_BANKRUPTCY_PRODUCT_KEY
		<tag>
			FIRST
			<value>P_NEW_BASIC</value>
		</tag>
		<tag>
			SECOND
			<value>P_REWARD</value>
		</tag>
	</section>
		
	<!---END OF BANKRUPTCY PRODUCTS-->
	
	
	<!--PRODUCTS LIST-->
	
	<section>
		LLOYDS_PRODUCTS_LIST
		<tag>
			FIRST
			<value>P_CLASSIC</value>
		</tag>
		<tag>
			SECOND
			<value>P_CLUB</value>
		</tag>
		<tag>
			THIRD
			<value>P_NEW_BASIC</value>
		</tag>
		<tag>
			FOURTH
			<value>P_PLAT</value>
		</tag>	
		<tag>
			FIFTH
			<value>P_PLAT_CLB</value>
		</tag>	
		<tag>
			SIXTH
			<value>P_STUDENT</value>
		</tag>	
		<tag>
			SEVENTH
			<value>P_UNDER19</value>
		</tag>
		<tag>
			EIGHTH
			<value>P_CASH</value>
		</tag>
		<tag>
			NINETH
			<value>P_GRADUATE</value>
		</tag>
		<tag>
			TENTH
			<value>P_SELECT</value>
		</tag>
		<tag>
			ELVENTH
			<value>P_SILVER</value>
		</tag>
		<tag>
			TWELVETH
			<value>P_GOLD</value>
		</tag>
		<tag>
			THIRTEENTH
			<value>P_PREMIER</value>
		</tag>							
	</section>

	<section>
		BOS_PRODUCTS_LIST
		<tag>
			FIRST
			<value>P_CLASSIC</value>
		</tag>
		<tag>
			SECOND
			<value>P_NEW_BASIC</value>
		</tag>
		<tag>
			THIRD
			<value>P_PLAT</value>
		</tag>
		<tag>
			FOURTH
			<value>P_UNDER19</value>
		</tag>	
		<tag>
			FIFTH
			<value>P_STUDENT</value>
		</tag>	
		<tag>
			SIXTH
			<value>P_CLSCVTG</value>
		</tag>
		<tag>
			SEVENTH
			<value>P_PLATVTG</value>
		</tag>
		<tag>
			EIGHTH
			<value>P_CASH</value>
		</tag>
		<tag>
			NINETH
			<value>P_GRADUATE</value>
		</tag>
		<tag>
			TENTH
			<value>P_ULTIMATE</value>
		</tag>
		<tag>
			ELVENTH
			<value>P_SILVER</value>
		</tag>
		<tag>
			TWELVETH
			<value>P_GOLD</value>
		</tag>
		<tag>
			THIRTEENTH
			<value>P_PREMIER</value>
		</tag>
	</section>
	
	
	<section>
		HALIFAX_PRODUCTS_LIST
		<tag>
			FIRST
			<value>P_REWARD</value>
		</tag>
		<tag>
			SECOND
			<value>P_ULTIMATE</value>
		</tag>
		<tag>
			THIRD
			<value>P_NEW_BASIC</value>
		</tag>
		<tag>
			FOURTH
			<value>P_STUDENT</value>
		</tag>	
		<tag>
			FIFTH
			<value>P_EXPRESSCASH</value>
		</tag>
		<tag>
			SIXTH
			<value>P_STANDARD</value>
		</tag>	
								
	</section>	

	<!--END OF PRODUCTS LIST-->
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configSchedulerService.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
       <section>
              RefreshSchedulerConfig
              
              <tag>
                     ReferenceDataRefreshScheduler.name
                     <value>ReferenceDataRefreshScheduler</value>
              </tag>
       </section>
       <!-- Added the MMRefDataRefreshScheduler for Money Manager Reference Data Refresh -->
       <section>
              LoadOnStartUp
              <tag>
                     InitialDelay
                     <value>5000</value>
              </tag>
       </section>      
      
       <!-- TMX fuse changes starts -->
       <section>
              FuseRetrievalScheduler
              <tag>
                     ClassName
                     <value>
                            com.lloydstsb.ea.scheduler.FuseRetrievalScheduler
                     </value>
              </tag>
              <tag>
                     LoadOnStartUp
                     <value>true</value>
              </tag>
              <tag>
                     RefreshType
                     <value>Regular</value>
              </tag>
              <tag>
                     RefreshTime
                     <value>60</value>
              </tag>
       </section>
       <section>
              FuseStateTransitionScheduler
              <tag>
                     ClassName
                     <value>
                            com.lloydstsb.ea.scheduler.FuseStateTransitionScheduler
                     </value>
              </tag>
              <tag>
                     LoadOnStartUp
                     <value>true</value>
              </tag>
              <tag>
                     RefreshType
                     <value>Regular</value>
              </tag>
              <tag>
                     RefreshTime
                     <value>60</value>
              </tag>
       </section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configCurrentAccountReferalCodes.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
    <section>
        currentAccountReferalCodesMapping
        <tag>
            003
            <value>Bureau</value>
        </tag>


        <tag>
            301
            <value>Bank</value>
        </tag>

        <tag>
            302
            <value>Bank</value>
        </tag>

        <tag>
            303
            <value>Bank</value>
        </tag>

        <tag>
            304
            <value>Bank</value>
        </tag>

        <tag>
            306
            <value>Bank</value>
        </tag>

        <tag>
            308
            <value>Bank</value>
        </tag>

        <tag>
            310
            <value>Bank</value>
        </tag>

        <tag>
            311
            <value>Bank</value>
        </tag>

        <tag>
            312
            <value>Bank</value>
        </tag>

        <tag>
            313
            <value>Bank</value>
        </tag>

        <tag>
            315
            <value>Bank</value>
        </tag>

        <tag>
            321
            <value>Bank</value>
        </tag>

        <tag>
            361
            <value>Bank</value>
        </tag>

        <tag>
            362
            <value>Bank</value>
        </tag>

        <tag>
            363
            <value>Bank</value>
        </tag>

        <tag>
            364
            <value>Bank</value>
        </tag>

        <tag>
            367
            <value>Bank</value>
        </tag>

        <tag>
            368
            <value>Bank</value>
        </tag>

        <tag>
            369
            <value>Bank</value>
        </tag>

        <tag>
            370
            <value>Bank</value>
        </tag>

        <tag>
            373
            <value>Bank</value>
        </tag>

        <tag>
            381
            <value>Bank</value>
        </tag>

        <tag>
            382
            <value>Bank</value>
        </tag>

        <tag>
            386
            <value>Bank</value>
        </tag>

        <tag>
            388
            <value>Bank</value>
        </tag>

        <tag>
            389
            <value>Bank</value>
        </tag>

        <tag>
            391
            <value>Bank</value>
        </tag>

        <tag>
            396
            <value>Bank</value>
        </tag>

        <tag>
            307
            <value>Bureau</value>
        </tag>

        <tag>
            314
            <value>Bureau</value>
        </tag>

        <tag>
            322
            <value>Bureau</value>
        </tag>

        <tag>
            323
            <value>Bureau</value>
        </tag>

        <tag>
            341
            <value>Bureau</value>
        </tag>

        <tag>
            365
            <value>Bureau</value>
        </tag>

        <tag>
            366
            <value>Bureau</value>
        </tag>

        <tag>
            387
            <value>Bureau</value>
        </tag>


        <tag>
            316
            <value>Duplicate</value>
        </tag>



    </section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configADAMGroupRoles.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
	<section>
	CURRENT_ACCOUNTS
	<tag>
		BTRPCA
		<value>GG_RETAIL_BRANCH_PCA_SELLER</value>
	</tag>
</section>
	<section>
		DOCUMENT_RETRIEVAL
		<tag>
			BTRPCA_01
			<value>GG_OAP_DOWNLOAD_01</value>
		</tag>
		<tag>
			BTRPCA_02
			<value>GG_OAP_DOWNLOAD_02</value>
		</tag>
		<tag>
			BTRPCA_03
			<value>GG_OAP_DOWNLOAD_03</value>
		</tag>						
	</section>
	
	<section>
		SAVENRESUMEWRITE
		<tag>
			BTRPCA_08
			<value>GG_RETAIL_BRANCH_AML_ACCRED</value>
		</tag>
	</section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configApiServiceProperties_Sandbox.xml
<?xml version="1.0"?>
<!DOCTYPE root SYSTEM "./config.dtd">
<root>
    <section>
        API_SERVICE_ENDPOINTS
        <tag>
            ADDRESS_SEARCH
            <!--<value><![CDATA[http://apigwproxy.lbg.eu-gb.mybluemix.net/sandbox-team-dev/dev/secure/InformationProvisionService?client_id=faf3ad00-0fa5-4d9c-92ae-1252e960fc2f&client_secret=lP7hU6wH5mL1kV4uF1kY0eW2mS8hU6gX0bM3uO0fJ8lB3sW6lV]]></value>-->
            <value>http://pca-stubs-client-master.lbg.eu-gb.mybluemix.net/stub/</value>
        </tag>
        <tag>
           RECORD_ARRANGEMENT_QUESTIONNAIRE_SERVICE
           <value><![CDATA[http://apigwproxy.lbg.eu-gb.mybluemix.net/sandbox-team-dev/dev/secure/wps/sales/v1.0/recordArrangementQuestionnaireResult?client_id=ebe44084-3522-4bb5-b080-784dfb400cab&client_secret=X4qE2oK6kW6gW6uA6gS5iP3eL3eR4gK5sD8hL1tS7sJ8yN5iO3]]></value>
         </tag>

		<tag>
            PRODUCT_HOLDING
            <!--<value>http://pao-service-stubs-sprint8-aco-mockservice.lbg.eu-gb.mybluemix.net/AccountsStub</value>-->
        	<value>http://pca-stubs-client-master.lbg.eu-gb.mybluemix.net/PCAAccountsStub</value>
        </tag>
         <tag>
			RETRIEVE_ARRANGEMENT_QUESTIONNAIRE_SERVICE
 			<value><![CDATA[http://apigwproxy.lbg.eu-gb.mybluemix.net/sandbox-team-dev/dev/secure/wps/sales/v1.0/retrieveArrangementQuestionnaire?client_id=ebe44084-3522-4bb5-b080-784dfb400cab&client_secret=X4qE2oK6kW6gW6uA6gS5iP3eL3eR4gK5sD8hL1tS7sJ8yN5iO3]]></value>
        </tag>
        <tag>
            TOKEN_VALIDATION
           <!--<value><![CDATA[https://public_apim_dev.lbg.eu-gb.bluemix.net/sandbox-team-dev/secure/InformationProvisionService?client_id=faf3ad00-0fa5-4d9c-92ae-1252e960fc2f&client_secret=lP7hU6wH5mL1kV4uF1kY0eW2mS8hU6gX0bM3uO0fJ8lB3sW6lV]]></value>-->
           <value><![CDATA[http://pca-stubs-client-master.lbg.eu-gb.mybluemix.net/PCAInvolvedPartyAuthorisationService]]></value>
        </tag>
    </section>

    <section>
        DEVICE_URL
        <tag>
            LLOYDS
            <value>https://check2.lloydsbank.co.uk</value>
        </tag>
        <tag>
            HALIFAX
            <value>https://check2.halifax-online.co.uk</value>
        </tag>
        <tag>
            BOS
            <value>https://check2.bankofscotland.co.uk</value>
        </tag>
        <tag>
            VERDE
            <value>https://check2.tsb.co.uk</value>
        </tag>
        <tag>
            LLOYDSBANK
            <value>https://check2.lloydsbank.co.uk</value>
        </tag>
    </section>

    <section>
        ThreatMetrixOrgID
        <tag>
            LLOYDS
            <value>g17j1ysn</value>
        </tag>
        <tag>
            HALIFAX
            <value>g17j1ysn</value>
        </tag>
        <tag>
            BOS
            <value>g17j1ysn</value>
        </tag>
        <tag>
            LLOYDSBANK
            <value>g17j1ysn</value>
        </tag>
        <tag>
            VERDE
            <value>8vzkivup</value>
        </tag>
    </section>

	<section>
		ThreatMetrixApiKey
		<tag>
			LLOYDS
			<value>irit8diagzvsojwmttfduhaj3tv9yuig</value>
		</tag>
		<tag>
			HALIFAX
			<value>irit8diagzvsojwmttfduhaj3tv9yuig</value>
		</tag>
		<tag>
			BOS
			<value>irit8diagzvsojwmttfduhaj3tv9yuig</value>
		</tag>
		<tag>
			LLOYDSBANK
			<value>irit8diagzvsojwmttfduhaj3tv9yuig</value>
		</tag>
		<tag>
			VERDE
			<value>irit8diagzvsojwmttfduhaj3tv9yuig</value>
		</tag>
	</section>
	
	<section>
        CONTENT
        <tag>
            LTSBRetail
            <value>http://sit-ib-pres-svr-content.service.test.group/wps/wcm/connect/devpreview_teamsite_lloyds_personal_banking/en/LloydsPersonalBanking/cwa/</value>
        </tag>
        <tag>
            BOSRetail
            <!-- <value>http://sit-ib-pres-svr-content.service.test.group/wps/wcm/connect/devpreview_teamsite_bos_personal_banking/en/BosPersonalBanking/cwa/</value> -->
            <value>http://apigwproxy.lbg.eu-gb.mybluemix.net/sandbox-team-dev/dev/content_secure/en/BosPersonalBanking/cwa/</value>
        </tag>
        <tag>
            HalifaxRetail
            <value>http://sit-ib-pres-svr-content.service.test.group/wps/wcm/connect/devpreview_teamsite_halifax_personal_banking/en/HalifaxPersonalBanking/cwa/</value>
        </tag>
    </section>
	<section>
		CONTENTSERVICE_URL_BRAND_NSP
		<tag>
			LTSBRetail
			<value>LloydsPersonalBanking/cwa/</value>
		</tag>
		<tag>
			BOSRetail
			<value>BosPersonalBanking/cwa/</value>
		</tag>
		<tag>
			HalifaxRetail
			<value>HalifaxPersonalBanking/cwa/</value>
		</tag>
	</section>
	
	<section>
        CONTENTSERVICE_URL_RESOURCE_BUNDLE_NSP
        <tag>
            LTSBRetail
            <value>sandbox-team-dev/sb/CG/content_secure/testpreview_teamsite_lloyds_personal_banking/</value>
        </tag>
        <tag>
            BOSRetail
            <value>sandbox-team-dev/sb/CG/content_secure/testpreview_teamsite_bos_personal_banking</value>
        </tag>
		<tag>
            HalifaxRetail
            <value>sandbox-team-dev/sb/CG/content_secure/testpreview_teamsite_halifax_personal_banking/</value>
        </tag>
    </section>

	<!-- <section>
		CONTENTSERVICE_URL_RESOURCE_BUNDLE_NSP
		<tag>
			LTSBRetail
			<value>devpreview_teamsite_lloyds_personal_banking</value>
		</tag>
		<tag>
			BOSRetail
			<value>devpreview_teamsite_bos_personal_banking</value>
		</tag>
		<tag>
			HalifaxRetail
			<value>devpreview_teamsite_halifax_personal_banking</value>
		</tag>
	</section> -->
	
	<section>
        IIS_CMS_SERVER_URL_NSP
        <tag>
            LTSBRetail
            <value>http://apigwproxy.lbg.eu-gb.mybluemix.net/</value>
        </tag>
        <tag>
            BOSRetail
            <value>http://apigwproxy.lbg.eu-gb.mybluemix.net/</value>
        </tag>
		<tag>
            HalifaxRetail
            <value>http://apigwproxy.lbg.eu-gb.mybluemix.net/</value>
        </tag>
    </section>

   <!--  <section>
        IIS_CMS_SERVER_URL_NSP
        <tag>
            LTSBRetail
            <value>http://pao-mock-service.lbg.eu-gb.mybluemix.net/content/wps/wcm/connect/</value>
        </tag>
        <tag>
            BOSRetail
            <value>http://pao-mock-service.lbg.eu-gb.mybluemix.net/content/wps/wcm/connect/</value>
        </tag>
		<tag>
            HalifaxRetail
            <value>http://pao-mock-service.lbg.eu-gb.mybluemix.net/content/wps/wcm/connect/</value>
        </tag>
    </section> --> 
    
    <section>
        CONTENTSERVICE_CLIENT_ID
        <tag>
            LTSBRetail
            <value>client_id=ddd443a0-02ef-499b-9fb5-b5b9b736487d</value>
        </tag>
        <tag>
            BOSRetail
            <value>client_id=ddd443a0-02ef-499b-9fb5-b5b9b736487d</value>
        </tag>
		<tag>
            HalifaxRetail
            <value>client_id=ddd443a0-02ef-499b-9fb5-b5b9b736487d</value>
        </tag>
    </section>
    
    <section>
        CONTENTSERVICE_CLIENT_SECRET
        <tag>
            LTSBRetail
            <value>client_secret=pR4yU3sG8lI0qK3iR4wQ3cK6dL6bS0xY3gQ3aD8gS5kM5rB3sU</value>
        </tag>
        <tag>
            BOSRetail
            <value>client_secret=pR4yU3sG8lI0qK3iR4wQ3cK6dL6bS0xY3gQ3aD8gS5kM5rB3sU</value>
        </tag>
		<tag>
            HalifaxRetail
            <value>client_secret=pR4yU3sG8lI0qK3iR4wQ3cK6dL6bS0xY3gQ3aD8gS5kM5rB3sU</value>
        </tag>
    </section>

	<section>
        SERVICES_CLIENT_ID
        <tag>
            PAMDB
            <value>client_id=ebe44084-3522-4bb5-b080-784dfb400cab</value>
        </tag>
    </section>
    
    <section>
        SERVICES_CLIENT_SECRET
        <tag>
            PAMDB
            <value>client_secret=X4qE2oK6kW6gW6uA6gS5iP3eL3eR4gK5sD8hL1tS7sJ8yN5iO3</value>
        </tag>
    </section>

	<section>
		TIMEOUTS
		<tag>
			SOAP_COMMUNICATOR_TIMEOUT_IN_MILLIS
			<value>5000</value>
		</tag>
		<tag>
			CONTENT_SERVICE_BACKEND_CALL_TIMEOUT_IN_MILLIS
			<value>5000</value>
		</tag>
	</section>
	<section>
		PRODUCT_SELECTOR_CONTENT
		<tag>
			CONTENT_PATH
			<value>savings/product/product_mnemonic</value>
		</tag>
		<tag>
			CONTENT_SERVICE_BACKEND_CALL_TIMEOUT_IN_MILLIS
			<value>5000</value>
		</tag>
	</section>
    <section>
        com.lloydstsb.gx.GalaxySystemParameter
        <tag>
            lloyds.client.web.application.container.uri
            <value>http://pca-stubs-client-master.lbg.eu-gb.mybluemix.net</value>
        </tag>
    </section>
    <section>
        IIS_CMS_SERVER_CONTEXT
        <tag>
            content.context.uri
            <value>ib/pb/cwa/refdata/pca-ref-data/</value>
        </tag>
    </section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configWafEvents.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
    <section>WAF_EVENT_CODE_PROCESSING
        <tag>ENABLED
            <value>OFF</value>
            <!-- Possible value ON/OFF -->
        </tag>      
    </section>
    <section>WAF_HEADERS_LIST
        <tag>HEADER_ONE
            <value>HEADER_SAMPLE</value>
        </tag>      
    </section>
    <section>WAF_EVENT_ERROR_CODE_MAPPING
        <tag>EVENT_SAMPLE
            <value>900001</value>
        </tag>  
        <tag>DEFAULT_ERROR_CODE
            <value>900000</value>
        </tag>  
    </section>
    <section>WAF_EVENT_HANDLING_MAPPING
        <tag>EVENT_SAMPLE
            <value>LOG</value>
            <!-- Possible value LOG/LOGOFF -->
        </tag>      
    </section>
</root>
