=== chetan03tutorial/gozo/sales-api/src/main/resources/config/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root (section+)>
<!ELEMENT section (#PCDATA | tag)*>
<!ELEMENT tag (#PCDATA | value)*>
<!ELEMENT value (#PCDATA)>
<!ATTLIST tag type CDATA #IMPLIED>
<!ATTLIST value type CDATA #IMPLIED>

<!--===============================================================================================-->
<!-- Entities -->
<!--===============================================================================================-->
<!--===============================================================================================-->
<!ENTITY URL_CMS_SERVER "http://10.245.225.17:10051">
<!ENTITY WA_PROVIDER_DOMAIN "statse.webtrendslive.com">
<!ENTITY WA_PROVIDER_DATASOURCE "dcsq8h85v000004zdphfmh9ls_6o3l">
<!ENTITY WA_PROVIDER_FIRST_PARTY_COOKIE_DOMAIN "test.lloydstsb.co.uk">
<!ENTITY WA_PROVIDER_ENABLED "false">
<!ENTITY GALAXY_LOG_DIR "${GalaxyLogDir}">
<!ENTITY URL_REFERER_INITIAL_REQUEST "https://ibglxystc-ltsb.test.lloydstsb.co.uk$$$https://ibglxystc-ltsbbusiness.test.lloydstsb.co.uk$$$https://ibglxystc.bos.test.lloydstsb.co.uk$$$https://ibglxystc-bosbusiness.test.lloydstsb.co.uk$$$https://ibglxystc-halifax.test.lloydstsb.co.uk$$$https://llgb-p1dc-dpw-wf07-eth0.test.lloydstsb.co.uk$$$https://galhsm.test.lloydstsb.co.uk$$$https://this.url.used.for.live.do.not.remove">
<!ENTITY URL_REFERER_OTHER_REQUEST "https://ibglxystc-ltsb.test.lloydstsb.co.uk$$$https://ibglxystc-ltsbbusiness.test.lloydstsb.co.uk$$$https://ibglxystc.bos.test.lloydstsb.co.uk$$$https://ibglxystc-bosbusiness.test.lloydstsb.co.uk$$$https://ibglxystc-halifax.test.lloydstsb.co.uk$$$https://llgb-p1dc-dpw-wf07-eth0.test.lloydstsb.co.uk$$$https://galhsm.test.lloydstsb.co.uk$$$https://this.url.used.for.live.do.not.remove">
<!ENTITY FORCED_LOGOFF_REDIRECT_URL "/sorry/pages/error.html">
<!ENTITY INVALID_SESSION_FORCED_LOGOFF_REDIRECT_URL "https://ibglxystc-ltsb.test.lloydstsb.co.uk:16222">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_LOGIN "/">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_1 "/sorry/pages/error.html">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_2 "/unauth/pages/customersecuritylogoff.jsp">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_SORRY_PAGE_3 "/unauth/pages/errorpageauthenticationfailed.jsp">
<!ENTITY FORCED_LOGOFF_REDIRECT_TO_UNAVAILABLE_PAGE "/sorry/pages/unavailable.html">
<!ENTITY URL_AUTH_SERVER "https://llgb-p1dc-dpw-wf07-eth0.test.lloydstsb.co.uk:16223/personal/login">
<!ENTITY URL_LTSB_RETAIL "https://ibglxystc-ltsb.test.lloydstsb.co.uk:16232/personal">
<!ENTITY URL_BOS_RETAIL "https://ibglxystc.bos.test.lloydstsb.co.uk:16232/InternetBankingUnauthWEB">
<!ENTITY COOKIES_DOMAIN ".lloydstsb.co.uk">
<!ENTITY THROTTLE_COOKIES_NAME "IBCOOKIE01">
<!ENTITY APPLICATION_LOGGING_MODE "UA">
<!ENTITY AUTH_SITE "false">
<!ENTITY TRAVEL_MONEY_BRANCH_FINDER_KEY "AvvQOc_Gq6nyV_8mWKgCcCe9aGXU6N6NhNptoM6_XvzWGBZYbcVx2rTX_HDFE-KT">
<!ENTITY MULTIMAP_URL_PREFIX "https://dev.virtualearth.net/REST/v1/Imagery/Map/Road/">
<!ENTITY MULTIMAP_URL_POSTFIX "&amp;err=No+map+available.&amp;width=250&amp;height=250&amp;scale=10000">
<!ENTITY STACK "UNAS">

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configApplicationContext.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
	<section>
		ApplicationContext
		<tag>
			APPLICATION_CONTEXT_APPLICATION_NAME
			<value>IB</value>
		</tag>
	</section>
	<section>
		ApplicationRequestContext
		<tag>
			APPLICATION_CONTEXT_CHANNEL
			<value>IBL</value>
		</tag>
		<tag>
			APPLICATION_CONTEXT_COMPONENT_NAME
			<value>Web IB</value>
		</tag>
		<tag>
			APP_TYPE_BRANCH
			<value>Branch</value>
		</tag>
		<tag>
			APP_TYPE_TELEPHONY
			<value>Telephony</value>
		</tag>
		<tag>
			APPLICATION_CONTEXT_COMPONENT_NAME_BRANCH
			<value>Branch Banking</value>
		</tag>
		<tag>
			APPLICATION_CONTEXT_COMPONENT_NAME_TELEPHONY
			<value>Telephony Banking</value>
		</tag>
	</section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configChannelMobileSupportMapping.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
    <section>
        CHANNEL_MOBILE_SUPPORT
        <tag>
            LTSBRetail
            <value>1</value>
        </tag>
        <tag>
            LTSBCommercial
            <value>0</value>
        </tag>
        <tag>
            BOSRetail
            <value>1</value>
        </tag>
        <tag>
            BOSCommercial
            <value>0</value>
        </tag>
        <tag>
            HalifaxRetail
            <value>1</value>
        </tag>
        <!--  Verde Changes - UI layer - starts -->
        <tag>
            VerdeRetail
            <value>0</value>
        </tag>
        <tag>
            VerdeCommercial
            <value>0</value>
        </tag>
        <!--  Verde Changes - UI layer - ends -->

    </section>
 
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configApplicationChannelMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
	<section>
		GIB
		<tag>
			LTSBRetail
			<value>LTSB.Retail</value>
		</tag>
		<tag>
			LTSBCommercial
			<value>LTSB.Comm</value>
		</tag>
		<tag>
			BOSRetail
			<value>BOS.Retail</value>
		</tag>
		<tag>
			BOSCommercial
			<value>BOS.Comm</value>
		</tag>
		<tag>
			HalifaxRetail
			<value>Hfx.Retail</value>
		</tag>
		<!-- Verde Changes - UI layer - starts -->
		<tag>
			VerdeRetail
			<value>VER.Retail</value>
		</tag>
		<tag>
			VerdeCommercial
			<value>VER.Comm</value>
		</tag>
		<!-- Verde Changes - UI layer - ends -->
	</section>

	<section>
		UA
		<tag>
			LTSBRetail
			<value>Retail</value>
		</tag>
		<tag>
			LTSBCommercial
			<value>Commercial</value>
		</tag>
		<tag>
			BOSRetail
			<value>Retail</value>
		</tag>
		<tag>
			BOSCommercial
			<value>Commercial</value>
		</tag>
		<tag>
			HalifaxRetail
			<value>Retail</value>
		</tag>
		<!-- Verde Changes - UI layer - starts -->
		<tag>
			VerdeRetail
			<value>Retail</value>
		</tag>
		<tag>
			VerdeCommercial
			<value>Commercial</value>
		</tag>
		<!-- Verde Changes - UI layer - ends -->
	</section>

	<section>
		APP_TYPE
		<tag>
			APP_TYPE_ID
			<value>&APPLICATION_LOGGING_MODE;</value>
		</tag>
	</section>

	<!-- STPCC Changes Start-->
	<section>
		AUTHENTICATION_TYPE
		<tag>
			AuthenticationValueType
			<value>&AUTH_SITE;</value>
		</tag>
	</section>
	<!-- STPCC Changes End-->
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configCommon.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
	<section>
		commonValue
		<tag>
			configured_logOff_count
			<value>-1</value>
		</tag>
	</section>
	<section>
		leadMsg
		<tag>
			age_limit
			<value>16</value>
		</tag>
	</section>
	<section>
		meminfo
		<tag>
			accesstoken_length
			<value>16</value>
		</tag>
	</section>
	<section>
		SessionConfiguration
		<tag>
			DefaultArrangementReminderDays
			<value>90</value>
		</tag>
		<tag>
			PrefetchWaitTime
			<value>60000</value>
		</tag>
		<tag>
			ThreadSleepTime
			<value>500</value>
		</tag>
		<tag>
			DefaultNoOfWorkerThreadsToTrigger
			<value>5</value>
		</tag>
	</section>
	<section>
		MobileFasterPaymentConfiguration
		<tag>
			FasterPaymentWaitTime
			<value>3000</value>
		</tag>
		<tag>
			ThreadSleepTime
			<value>500</value>
		</tag>
	</section>

	<section>
		logBackURL
		<tag>
			LoginURL
			<value>&INVALID_SESSION_FORCED_LOGOFF_REDIRECT_URL;</value>
		</tag>
	</section>
	<!--  International Payment reference Data loader -->
	<section>
		INTERNATIONAL_PAYMENT_LOADER_SETTING
		<tag>
			CLASSIFICATION_KEY
			<value>InternationalPayment</value>
		</tag>
	</section>
	<!--  Mobile Interstitial LEADS URL possible values -->
	<section>
		LEADS_URL_VALUES
		<tag>
			TELE_LINK
			<value>tel:</value>
		</tag>
	</section>
	<!--  Flag to identify whether we should allow future dated statements, to be changed via x-path, added for paperless -->
	<section>
		B2K_VIEW_STATEMENTS
		<tag>
			ALLOW_FUTURE_DATED_STATEMENTS
			<value>false</value>
		</tag>
	</section>
	<!--  Minimum loan amount customer can borrow in Eloan refinance -->
	<section>
		Eloan_Refinance_Min_Amount
		<tag>
			Min_Loan_Amount
			<value>1000</value>
		</tag>
	</section>
	<!--  ISA Transfer reference Data loader -->
	<section>
		ISA_TRANSFER_LOADER_SETTING
		<tag>
			CLASSIFICATION_KEY
			<value>ISATransfer</value>
		</tag>
	</section>
	<!-- Added for Sampson -->
	<section>
        UnauthURL
        <tag>
          	LLOYDS
             <value>https://apply.lloydsbank.co.uk/personal/a</value>
        </tag>
    </section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configDeviceManagement.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
    <section>
        Default
        <tag type="string">
            LaunchURL
            <value type="string">/logon/login.jsp</value>
        </tag>
        <!-- EA component config file change : start -->
        <tag>
            RegisterURL
            <value>
                /a/registration/onlinepersonalregistration.jsp
            </value>
        </tag>
        <tag type="String">
            URLPattern
            <value type="string">/mobile</value>
        </tag>
        <tag type="String">
            ForwardMode
            <value type="string">true</value> <!-- true for unauth and false for auth environment -->
        </tag>
        <tag type="String">
            RedirectURL
            <value type="string">/useradmin/mobile/logon/login.jsp</value>
        </tag>
        <tag>
            RedirectRegisterURL
            <value>
                /a/useradmin/mobile/registration/selectaccounttyperegistration.jsp
            </value>
        </tag>
         <tag>
            NGB_DEVICE_DETECTION
            <value>true</value><!-- true to enable NGB device detection -->
        </tag>
                <tag>
            NGB_CAPABILITIES_CACHING
            <value>true</value><!-- true to enable NGB capabilities caching -->
        </tag>
        <tag type="String">
            ErrorPagePasswordURL
            <value type="string">/a/common/mobile/errorpagepassword.jsp</value>
        </tag>
            <tag type="String">
            BrappBlockedURL
            <value type="string">/unauth/pages/Blockbrapppage.jsp</value>
        </tag>
        <tag>
            AuthenticationFailedURL
            <value>
                /unauth/pages/errorpageauthenticationfailed.jsp
            </value>
        </tag>
        <tag type="String">
            BrappBlockedURL
            <value>
                /unauth/pages/Blockbrapppage.jsp
            </value>
        </tag>
        <tag>
            AuthenticationFailedURL
            <value>
                /unauth/pages/errorpageauthenticationfailed.jsp
            </value>
        </tag>
        <tag type="String">
            APP_PARAM
            <value>
                app
            </value>
        </tag>
        <tag type="String">
            APP_PARAM_VALUE
            <value>
                brapp
            </value>
        </tag>
        
        <tag>
            HUB_PAGE_URL
            <value>
                /a/viewaccount/accountoverviewpersonalbase.jsp
            </value>
        </tag>
         <tag>
            STACK_TYPE
            <value>&STACK;</value>
        </tag>
        
    </section>
    <section>
        UnAuthNonBookmarkURL
        <tag>
            ErrorPagePasswordURL
            <value>/a/common/mobile/errorpagepassword.jsp</value>
        </tag>
        <tag>
            SelectAccountTypeRegistration
            <value>
                /a/useradmin/mobile/registration/selectaccounttyperegistration.jsp
            </value>
        </tag>
        <tag>
            OnlinePersonalRegistration
            <value>
                /a/useradmin/mobile/registration/onlinepersonalregistration.jsp
            </value>
        </tag>
        <!-- EA component config file change : start -->
        <tag >
            OnlineRegistration
            <value >
                /a/registration/onlinepersonalregistration.jsp
            </value>
        </tag>
        <!-- EA component config file change : end -->
        
        <tag>
            ErrorPageLoggedOut
            <value>/a/common/mobile/errorpageloggedout.jsp</value>
        </tag>
        <tag>
            HelpDeskAuthorization
            <value>
                /a/useradmin/mobile/registration/helpdeskauthorization.jsp
            </value>
        </tag>
        <tag>
            SuccessRegistration
            <value>
                /a/useradmin/mobile/registration/successregistration.jsp
            </value>
        </tag>
        <tag>
            TermsAndConditions
            <value>
                /a/useradmin/mobile/registration/termsandconditions.jsp
            </value>
        </tag>

    </section>
    <section>
        AUTH_LOGGED_OFF_PAGES

        <tag>
            /unauth/pages/mobiledefault/paymentdeclined.jsp
            <value>/unauth/pages/mobiledefault/paymentdeclined.jsp</value>
        </tag>
        <tag>
            /unauth/pages/mobiledefault/phoneauthfailurefraudsuspected.jsp
            <value>/unauth/pages/mobiledefault/phoneauthfailurefraudsuspected.jsp
            </value>
        </tag>
        <tag>
            /unauth/pages/mobiledefault/errorpagepassword.jsp
            <value>/unauth/pages/mobiledefault/errorpagepassword.jsp</value>
        </tag>
        <tag>
            /unauth/pages/errorpageauthenticationfailed.jsp
            <value>/unauth/pages/errorpageauthenticationfailed.jsp</value>
        </tag>

    </section>
    <section>
        WURFL_MANDATE_CAPABILITIES
        <tag>
            mobile_browser
            <value>null</value>
        </tag>
        <tag>
            is_wireless_device
            <value>null</value>
        </tag>
        <tag>
            is_tablet
            <value>null</value>
        </tag>
        <tag>
            device_os_version
            <value>null</value>
        </tag>
        <tag>
            device_os
            <value>null</value>
        </tag>
        <tag>
            preferred_markup
            <value>null</value>
        </tag>
        <tag>
            resolution_height
            <value>null</value>
        </tag>
        <tag>
            resolution_width
            <value>null</value>
        </tag>
        <tag>
            ux_full_desktop
            <value>null</value>
        </tag>
        <tag>
            xhtml_support_level
            <value>null</value>
        </tag>
    </section>
    <section>
        GALAXY_SPECIFIC_CAPABILITIES
        <tag>
            screen_diagonal
            <value>physical_screen_width:physical_screen_height</value>
        </tag>
    </section>
    <section>
        DEVICE_SNIFFING_BLOCK_ERROR
        <tag>
            ERROR_CODE
            <value>3200008</value>
        </tag>
        <tag>
            ERROR_DESC
            <value>Prevent the device accessing the journey</value>
        </tag>
    </section>

</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configHandler.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>      
    <section>HANDLERS
        <tag>RESPONSE_HANDLER_KEY
            <value>RESPONSE_HANDLER</value>
        </tag>
        <tag>REQUEST_HANDLER_KEY
            <value>REQUEST_HANDLER</value>
        </tag>
        <!-- <tag>MALWARE_REQUEST_HANDLER_KEY
            <value>MALWARE_REQUEST_HANDLER</value>
        </tag> -->
    </section>
    <section>
        RESPONSE_HANDLER
        <tag>
            IP_ADDRESS_KEY
            <value>IP_ADDRESS_HANDLER</value>
        </tag>
    </section>  
    <section>
        REQUEST_HANDLER
        <tag>
            THROTTLE_HANDLER_KEY
            <value>THROTTLE_HANDLER</value>
        </tag>
        <tag>
            FORCE_LOGOUT_KEY
            <value>FRAUD_ACTION_HANDLER</value>
        </tag>
    </section>  
    <!-- <section>
        MALWARE_REQUEST_HANDLER
        <tag>
            MALWARE_HANDLER_KEY
            <value>MALWARE_HANDLER</value>
        </tag>
    </section> -->
    <section>
        IP_ADDRESS_HANDLER
        <tag>
            NAME
            <value>IP_ADDRESS_HANDLER</value>
        </tag>
        <tag>
            SWITCH_STATUS
            <value>ON</value>
            <!--  The possible values of HANDLER_ORDER are ON/OFF -->
        </tag>
        <tag>
            HANDLER_ORDER
            <value>1</value>            
        </tag>
        <tag>FAILOVER_ACTION
            <value>CONTINUE</value>
        </tag>
        <tag>
            HANDLER_CLASS
            <value>
                com.lloydstsb.ea.filters.securityfilter.handler.impl.FunctionalEventHandler
            </value>
        </tag>
    </section>  
    <section>
        THROTTLE_HANDLER
        <tag>
            NAME
            <value>THROTTLE_HANDLER</value>
        </tag>
        <tag>
            SWITCH_STATUS
            <value>ON</value>
            <!--  The possible values of HANDLER_ORDER are ON/OFF -->
        </tag>
        <tag>
            HANDLER_ORDER
            <value>1</value>
        </tag>
        <tag>FAILOVER_ACTION
            <value>CONTINUE</value>
            <!--  The possible values of FAILOVER_ACTION are CONTINUE/ABORT -->
        </tag>
        <tag>
            HANDLER_CLASS
            <value>
                com.lloydstsb.ea.filters.securityfilter.handler.impl.ThrottleActionHandler
            </value>
        </tag>
    </section>
    <section>
        FRAUD_ACTION_HANDLER
        <tag>
            NAME
            <value>FRAUD_ACTION_HANDLER</value>
        </tag>
        <tag>
            SWITCH_STATUS
            <value>ON</value>
            <!--  The possible values of HANDLER_ORDER are ON/OFF -->
        </tag>
        <tag>
            HANDLER_ORDER
            <value>2</value>
        </tag>
        <tag>FAILOVER_ACTION
            <value>CONTINUE</value>
            <!--  The possible values of FAILOVER_ACTION are CONTINUE/ABORT -->
        </tag>
        <tag>
            HANDLER_CLASS
            <value>
                com.lloydstsb.ea.filters.securityfilter.handler.impl.FraudActionHandler
            </value>
        </tag>
    </section>
    <section>
        LOGGING_HANDLER
        <tag>
            NAME
            <value>LOGGING_HANDLER</value>
        </tag>
        <tag>
            SWITCH_STATUS
            <value>ON</value>
            <!--  The possible values of HANDLER_ORDER are ON/OFF -->
        </tag>
        <tag>
            HANDLER_ORDER
            <value>2</value>
        </tag>
        <tag>FAILOVER_ACTION
            <value>CONTINUE</value>
            <!--  The possible values of FAILOVER_ACTION are CONTINUE/ABORT -->
        </tag>
        <tag>
            HANDLER_CLASS
            <value>
                com.lloydstsb.ea.filters.securityfilter.handler.impl.LoggingHandler
            </value>
        </tag>
    </section>  
    <!-- <section>
        MALWARE_HANDLER
        <tag>
            NAME
            <value>MALWARE_HANDLER</value>
        </tag>
        <tag>
            SWITCH_STATUS
            <value>ON</value>
             The possible values of HANDLER_ORDER are ON/OFF
        </tag>
        <tag>
            HANDLER_ORDER
            <value>1</value>
        </tag>
        <tag>FAILOVER_ACTION
            <value>CONTINUE</value>
             The possible values of FAILOVER_ACTION are CONTINUE/ABORT
        </tag>
        <tag>
            HANDLER_CLASS
            <value>
                com.lloydstsb.ea.malware.handler.impl.MalwareEventHandler
            </value>
        </tag>
    </section> -->
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configDocUploadAttributes.xml
<?xml version="1.0"?>
<!DOCTYPE Root SYSTEM "./config.dtd">

<root>
     <section>
        DOC_UPLOAD_SWITCH
        <tag>
            BRANDED_SWITCH
            <value>SW_EnDcUpldRApi</value>
        </tag>
    </section>

    <section>
        DOC_UPLOAD_SAVE_OPTION
        <tag>
            DOC_UPLOAD_SAVE_OPTION
            <value>N</value>
        </tag>
    </section>

<section>
        DOC_UPLOAD_FILTER
        <tag>
            JWT_VALID_TOKEN_COUNT
            <value>5</value>
        </tag>
        <tag>
            JWT_REQUEST_TOKEN
            <value>X-ACCESS-TOKEN</value>
        </tag>
    </section>
    <section>
        DOC_UPLOAD_CASE_STATUS
        <tag>
            OPEN_STATUS
            <value>OP</value>
        </tag>
        <tag>
            SUBMIT_STATUS
            <value>SB</value>
        </tag>
    </section>
    <section>
        DOC_UPLOAD_OPERATION_TYPE
        <tag>
            PREVIEW
            <value>PREVIEW</value>
        </tag>
        <tag>
            DELETE
            <value>DELETE</value>
        </tag>
        <tag>
            SUBMIT
            <value>SUBMIT</value>
        </tag>
        <tag>
            UPLOAD
            <value>UPLOAD</value>
        </tag>
    </section>
    <section>
        DOC_UPLOAD_SCAN_STATUS
        <tag>
            403
            <value>SF</value>
        </tag>
        <tag>
            413
            <value>LF</value>
        </tag>
        <tag>
            415
            <value>WT</value>
        </tag>
        <tag>
            405
            <value>AS</value>
        </tag>
        <tag>
            500
            <value>SE</value>
        </tag>
    </section>
     <section>
        DOC_UPLOAD_PROCESS_CODE
        <tag>
            AOOIDV-ON-LTB
            <value>AOOIDV-ON-LTB</value>
        </tag>
        <tag>
            Mortgage_Roll_Number
            <value>Mortgage_Roll_Number</value>
        </tag>
    </section>
</root>

=== chetan03tutorial/gozo/sales-api/src/main/resources/config/configLoggedOffPages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Root SYSTEM "./config.dtd">
<root>
    <section>
        LOGGED_OFF_PAGES_URI
        <tag>
            /unauth/pages/ErrorPageLoggedOut.jsp
            <value>/unauth/pages/ErrorPageLoggedOut.jsp</value>
        </tag>  
        <tag>
            /unauth/pages/errorpageauthenticationfailed.jsp
            <value>/unauth/pages/errorpageauthenticationfailed.jsp</value>
        </tag>  
        <tag>
            /unauth/pages/customersecuritylogoff.jsp
            <value>/unauth/pages/customersecuritylogoff.jsp</value>
        </tag>
        <tag>
            /unauth/pages/errorPageCustomerSecurityFailure.jsp
            <value>/unauth/pages/errorPageCustomerSecurityFailure.jsp</value>
        </tag>
    </section>
</root>
